### ISSUE TITLE
Comparison to alternate patcher?

### ISSUE THREAD

**Issue by piebaker** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#15]
Serialization is bad has also just been published to mitigate this issue, which would be better to use?
https://github.com/dogboy21/serializationisbad

**Comment by xyzeva** [comment]
It depends on what you value, security, or things breaking

SerialisationIsBad's tool blocks things they only know of, not all things like PipeBlocker

PipeBlocker protects proactively and fixes the root of the issue here, things break at first when mods are not added to our whitelist (*the whitelist only allows safe things to go over the network*), but its generally better for security.
